name: Release
on:
  # will run for every branch, except tags. See RSRMID-206.
  push:
    branches: [master]
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    name: 🧪 npm test
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18', '16', '14', '12']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip -V
          pip install -r requirements.txt
      - name: Validate & Coverage Report
        run: './scripts/pep8check.sh'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run test/validation
        run: |
          gulp prettierCheck
          npm run lint
          npm run test --silent >/dev/null
